// Cooking talk
IF
    InParty(Myself)
    See(Player1)
    !StateCheck("Nephele",CD_STATE_NOTVALID)
    !StateCheck(Player1,CD_STATE_NOTVALID)
    RealGlobalTimerExpired("LK#NepheleCookingTimer","GLOBAL")
    CombatCounter(0)
    !See([ENEMY])
    Global("LK#NepheleCooking","GLOBAL",2)
    AreaType([OUTDOOR])
THEN
  RESPONSE #100
    SetGlobal("LK#NepheleCooking","GLOBAL",3)
    MoveToObject(Player1)
    Dialogue(Player1)
END